{{- if and (not .Values.currentNamespaceOnly) .Values.webhook.enabled .Values.webhook.cert.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-enterprise-operator.fullname" . }}-webhook-ca
  labels:
    {{- include "mariadb-enterprise-operator-webhook.labels" . | nindent 4 }}
    mariadb-enterprise-operator.io/component: webhook
  {{- with .Values.webhook.cert.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-enterprise-operator.fullname" . }}-webhook-cert
  labels:
    {{- include "mariadb-enterprise-operator-webhook.labels" . | nindent 4 }}
    mariadb-enterprise-operator.io/component: webhook
  {{- with .Values.webhook.cert.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
